name:  Proxy deployment

on:
  workflow_dispatch:
    
    inputs:
      deployment-env:
        type: choice
        required : true
        description: Environment to deploy
        options: 
        - eval
        - dev
        - test
        - uat
        - stage
        - prod
      deployment-region:
        type: choice
        description: Region to deploy
        options: 
        - esi-apigee-x-394004
        - NA
      deployment-action:
        type: choice
        description:  Import only or deploy also ?
        options: 
        - import
        - deploy
     
  
env:
  # Retrieve GPC Workload Identity Provider and Service account from repository settings (secrets)
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  DEPLOYMENT_ACTION: ${{ github.event.inputs.deployment-action}}

  
jobs:
  Apigee-Deploy:
    
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: 'projects/127369686749/locations/global/workloadIdentityPools/github-test/providers/github-test'
            service_account: 'workload-identity-federation@esi-apigee-x-394004.iam.gserviceaccount.com'
            token_format: 'access_token'
            access_token_lifetime: '300s'

  # Setup Maven & Maven Cache
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: 11

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2   




  # Deploy Apigee Config (Apigee [Config] Maven plugin)
      
      - name: mvn deploy config
        run: mvn install -P eval -Dbearer='${{ steps.auth.outputs.access_token }}' -Dapigee.org=${{ github.event.inputs.deployment-region }} -Denv=${{ github.event.inputs.deployment-env}} -Dapigee.config.dir=./ApigeeConfig -Dapigee.config.options=update


 

    
